#!/bin/bash -e

for i in {1..5}; do
	ip_address=$(python -c "import socket; print socket.gethostbyname('$OPENSHIFT_GEAR_DNS')") && break || sleep 1
done

if [ -z "$ip_address" -o "$ip_address" == '0.0.0.0' ]; then
	ip_address="$(facter ipaddress)"
fi

echo $ip_address:$OPENSHIFT_ELASTICSEARCH_TRANSPORT_PROXY_PORT
